-- Generated by Oracle SQL Developer Data Modeler 17.3.0.261.1529
--   at:        2019-03-26 17:19:43 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Ad 
    (
     AdID INTEGER NOT NULL , 
     targetURL VARCHAR (1000) NOT NULL , 
     title VARCHAR (30) NOT NULL , 
     longTitle VARCHAR (90) NOT NULL , 
     description VARCHAR (90) NOT NULL , 
     companyName VARCHAR (30) NOT NULL , 
     nOfViews INTEGER NOT NULL , 
     AdGroupID INTEGER NOT NULL , 
     URL VARCHAR (895) NOT NULL , 
     imageID INTEGER 
    )
    ON "default"
GO
ALTER TABLE Ad 
    ADD CONSTRAINT Ad_AdGroup_FK FOREIGN KEY 
    ( 
     AdGroupID
    ) 
    REFERENCES AdGroup 
    ( 
     AdGroupID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION
GO
ALTER TABLE Ad 
    ADD CONSTRAINT Ad_Image_FK FOREIGN KEY 
    ( 
     imageID
    ) 
    REFERENCES Image 
    ( 
     imageID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION
GO
ALTER TABLE Ad 
    ADD CONSTRAINT Ad_WebPage_FK FOREIGN KEY 
    ( 
     URL
    ) 
    REFERENCES WebPage 
    ( 
     URL 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION
GO
ALTER TABLE Ad ADD CONSTRAINT Ad_PK PRIMARY KEY CLUSTERED (AdID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default"